# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOPg1wH0BQh72eeZdJ8dRZrhpKsV8_yk
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
mylabels=["SI", "diskret","kiber","algebra"]
plt.pie(x, labels=mylabels)
plt.show()

